C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik1.bmp sieve1.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik1.bmp sieve1.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik2.bmp sieve2.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik2.bmp sieve2.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik3.bmp sieve3.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik3.bmp sieve3.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik4.bmp sieve4.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik4.bmp sieve4.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik5.bmp sieve5.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik5.bmp sieve5.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp erozja2\wynik6.bmp sieve6.txt e
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp erozja3\wynik6.bmp sieve6.txt e

C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik1.bmp sieve1.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik1.bmp sieve1.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik2.bmp sieve2.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik2.bmp sieve2.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik3.bmp sieve3.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik3.bmp sieve3.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik4.bmp sieve4.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik4.bmp sieve4.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik5.bmp sieve5.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik5.bmp sieve5.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp dylatacja2\wynik6.bmp sieve6.txt d
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp dylatacja3\wynik6.bmp sieve6.txt d

C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik1.bmp sieve1.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik1.bmp sieve1.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik2.bmp sieve2.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik2.bmp sieve2.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik3.bmp sieve3.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik3.bmp sieve3.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik4.bmp sieve4.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik4.bmp sieve4.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik5.bmp sieve5.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik5.bmp sieve5.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp otwarcie2\wynik6.bmp sieve6.txt o
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp otwarcie3\wynik6.bmp sieve6.txt o

C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik1.bmp sieve1.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik1.bmp sieve1.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik2.bmp sieve2.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik2.bmp sieve2.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik3.bmp sieve3.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik3.bmp sieve3.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik4.bmp sieve4.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik4.bmp sieve4.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik5.bmp sieve5.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik5.bmp sieve5.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample2.bmp zamkniecie2\wynik6.bmp sieve6.txt c
C:\Users\narxyz\source\repos\bd6a470b-gr05-repo\Projekt\project_1\Debug\project_1.exe sample3.bmp zamkniecie3\wynik6.bmp sieve6.txt c